services:
  db:
    container_name: mysql_resellmart
    image: mysql:9.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resellmart_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - resellmart_network
    restart: unless-stopped
  mail-dev:
    container_name: mail_dev_resellmart
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db_data:
    driver: local

networks:
  resellmart_network:
    driver: bridge

