server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://mysql-resellmart:3306/resellmart_db?allowPublicKeyRetrieval=true&useSSL=false"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database: mysql
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: resellmartmail@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: 3600000 # 1 hour
      refresh-token:
        expiration: 604800000 # 1 week

    cors:
      allowed-origins: ${FRONTEND_URL}

  backend:
    base-https-url: ${VITE_API_URL}
  frontend:
    base-url: ${FRONTEND_URL}

  mailing:
    activation-url: "/auth/activation?code="

  stripe:
    secret-key: ${STRIPE_SECRET_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}
    checkout-success-url: "/app/my-purchases"
    checkout-cancel-url: "/app/checkout"

  file:
    upload:
      product-images-path: ./uploads/product-images
      user-images-path: ./uploads/user-images
      order-item-images-path: ./uploads/order-item-images
